Update README.md for transition to Hiero
hiero-ledger/hiero-sdk-swift pull request #394
Opened 2024-10-04 10:35 UTC by hendrikebbers

Should be merged shortly before the transition of the repo happens

2024-11-07 21:10 UTC, RickyLB requested changes
Small nit

2024-11-26 18:07 UTC, SimiHunjan commented
should we merge this once we move to Hiero or now?

2025-02-06 15:31 UTC, andrewb1269hg requested changes

2025-02-11 01:02 UTC, RickyLB approved these changes

2025-02-11 21:24 UTC, RickyLB approved these changes

2025-02-12 21:48 UTC, RickyLB commented
@andrewb1269hg Everything seems to be resolved– PR just need your approval. Thanks!

2025-02-12 21:55 UTC, andrewb1269hg approved these changes

2025-02-12 21:55 UTC, andrewb1269hg commented
@hendrikebbers looks like everything is good to go!

2025-02-12 21:56 UTC, merged